version: '3.8'

services:
  db:
    build:
      context: ./db-data
      dockerfile: Dockerfile 
    environment:
      POSTGRES_DB: betmeDb
      POSTGRES_USER: DrTau
      POSTGRES_PASSWORD: MyPassword
    ports:
      - "5432:5432"

  api:
    build:
      context: ./Betme-backend
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=betmeDb;Username=DrTau;Password=MyPassword
    ports:
      - "5091:5091"
    depends_on:
      - db

  frontend:
    build:
      context: ./Betme-frontend
      dockerfile: Dockerfile
    environment:
      - backend__path=localhost:5091
    ports:
      - "8080:8080"
    depends_on:
      - api

volumes:
  db-data:
